### ISSUE TITLE
Warning: Missing dependency 'joshcooper-powershell'

### ISSUE THREAD

**Issue by NetworkBytes** [noma4i/puppet-windows_updates#1]
Now that Puppetlabs-powershell is the supported standard 
can this module be updated to use that as a dependency 

Note the two modules cannot be installed  johncooped and puppetlabs powershell can not be installed on the same host

```
Warning: Missing dependency 'joshcooper-powershell':
  'noma4i-windows_updates' (v0.2.1) requires 'joshcooper-powershell' (>= 0.0.5 <5.0.0)
```

```
# puppet module install joshcooper-powershell --environment=development
Notice: Preparing to install into /etc/puppetlabs/code/environments/development/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'joshcooper-powershell' (latest)
  Installation would overwrite /etc/puppetlabs/code/environments/development/modules/powershell
    Currently, 'puppetlabs-powershell' (v1.0.4) is installed to that directory
    Use `puppet module install --force` to install this module anyway

```

**Comment by noma4i** [comment]
Sure! Will do this today

**Comment by NetworkBytes** [comment]
wow, that was a speedy response ...
you must be in the southern hemisphere or either working late
Thanks

**Comment by noma4i** [comment]
Sydney. Australia ;)

**Comment by evilmex** [comment]
Hello, I was wondering if this was dropped a while back.  Looks like its is still referencing the "joshcooper-powershell" I was just tried to install and received the same error as above.

**Comment by noma4i** [comment]
Im lazy bustard ;) PR highly appreciated

**Comment by noma4i** [comment]
Iv dropped dependency.

**Comment by evilmex** [comment]
Cool, thanks for updating it.  I see that in the code here, does it eventually sync up the the puppet forge?  Because when i try and install from the forge it still has the conflict. 
puppet module install noma4i-windows_updates
Notice: Preparing to install into /etc/puppetlabs/puppet/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'noma4i-windows_updates' (latest)
  Dependency 'joshcooper-powershell' (v0.0.6) would overwrite /etc/puppetlabs/puppet/environments/production/modules/powershell
    Currently, 'puppetlabs-powershell' (v1.0.5) is installed to that directory
    Use `puppet module install --ignore-dependencies` to install only this module
